_src_path: ../../charts/template
app_version: 2024.5.5
description: ' ğŸ¡ Open source home automation that puts local control and privacy first. '
homepage: https://www.home-assistant.io/
image: ghcr.io/linuxserver/homeassistant
keywords: automation
mariadb_enabled: false
name: homeassistant
port: 8123
postgresql_enabled: false
redis_enabled: false
root_directory: ../..
sources: https://github.com/home-assistant/core,https://github.com/linuxserver/docker-homeassistant
version: 0.1.28
